name:                kucoin-sdk
version:             0.1.0.0
github:              "/kucoin-sdk"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/kucoin-sdk#readme>

default-extensions:
  - RankNTypes
  - ScopedTypeVariables
  - DataKinds
  - BangPatterns
  - PolyKinds
  - ExistentialQuantification
  - TypeFamilies
  - TypeOperators
  - TypeApplications
  - GADTs
  - OverloadedStrings
  - InstanceSigs
  - EmptyCase
  - StandaloneKindSignatures
  - TemplateHaskell
  - TypeInType
  - UndecidableInstances
  - InstanceSigs
  - NoStarIsType
  - QuantifiedConstraints
  - DeriveGeneric
  - MultiParamTypeClasses
  - QuantifiedConstraints


dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- wreq
- lens
- base64
- cryptonite
- utf8-string
- aeson
- network
- vector
- async
- uuid
- http-types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  kucoin-sdk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kucoin-sdk

tests:
  kucoin-sdk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kucoin-sdk
